name: Run Cypress Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 12:00 AM UTC (5:30 AM IST)
  workflow_dispatch:  # Allows manual trigger

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0  # Match your local Node.js version

      - name: Cache Cypress Binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress  # Cache the Cypress binary
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Install Cypress Binary
        run: npx cypress install  # Explicitly install the Cypress binary

      - name: Verify Cypress Installation
        run: npx cypress verify  # Ensures Cypress is installed correctly

      - name: Run Cypress Tests (Attempt 1)
        id: test-attempt-1
        continue-on-error: true
        run: npx cypress run  # Run tests with npx to avoid path issues

      - name: Wait for 15 minutes before retrying (if failed)
        if: failure() && steps.test-attempt-1.outcome == 'failure'
        run: sleep 900  # 900 seconds = 15 minutes

      - name: Run Cypress Tests (Attempt 2)
        if: failure() && steps.test-attempt-1.outcome == 'failure'
        run: npx cypress run  # Retry Cypress tests 